### ISSUE TITLE
Update to new caltrain schedule?

### ISSUE THREAD

**Issue by yiransheng** [parshap/nextcaltrain#2]
Caltrain has changed the schedule since 04/10/17

http://www.caltrain.com/schedules/weekdaytimetable.html

**Comment by parshap** [comment]
I updated this a few days ago -- 2.1.5 should have the latest schedule. Are you seeing otherwise?

**Comment by parshap** [comment]
Here's the commit that pulled in the new GTFS data: https://github.com/parshap/nextcaltrain/commit/0614a283a567f18cdd4aac9f7965133def8b79ef

**Comment by yiransheng** [comment]
Thanks a lot!
